Hw shoppingcart
LaverAndrii/Book-Store pull request #11
Opened 2024-04-19 12:51 UTC by LaverAndrii

2024-04-19 13:09 UTC, kerrrusha requested changes

2024-04-19 13:09 UTC, koval-kn commented on src/main/java/mate/academy/bookstore/service/ShoppingCartServiceImpl.java
> +        throw new EntityNotFoundException("There is no such item in the shopping cart");
better invert this to avoid redundant identation
```suggestion
        if (!checkUser(cartId, email)) {
            throw new EntityNotFoundException("There is no such item in the shopping cart");
        }
        cartItemService.updateQuantity(cartId, updateQuantityDto.quantity());
        return shoppingCartMapper.toDto(getShoppingCartByEmail(email));
    }

    @Override
    public ShoppingCartDto removeBook(Long cartId, String email) {
        if (!checkUser(cartId, email)) {
            throw new EntityNotFoundException("There is no such item in the shopping cart");
        }
        cartItemRepository.deleteById(cartId);
        return getShoppingCart(email);
```

2024-04-19 13:09 UTC, kerrrusha commented on src/main/java/mate/academy/bookstore/service/ShoppingCartServiceImpl.java
> +                () -> new EntityNotFoundException("Can't find shopping cart by email " + email));
you should create it if it not exists

2024-04-20 13:09 UTC, MAMentorFX requested changes

2024-04-20 13:09 UTC, MAMentorFX commented on src/main/java/mate/academy/bookstore/controller/ShoppingCartController.java
> +        User user = (User) authentication.getPrincipal();
extract to a method to remove duplicates

2024-04-20 13:09 UTC, MAMentorFX commented on src/main/java/mate/academy/bookstore/mapper/ShoppingCartMapper.java
> +
```suggestion
```

2024-04-20 13:09 UTC, MAMentorFX commented on src/main/java/mate/academy/bookstore/service/CartItemServiceImpl.java
> +    }
@Transactional. You make more than one call to DB

2024-04-20 13:09 UTC, MAMentorFX commented on src/main/java/mate/academy/bookstore/service/ShoppingCartServiceImpl.java
> +    }
@Transactional. You make more than one call to DB

2024-04-20 13:09 UTC, MAMentorFX commented on src/main/java/mate/academy/bookstore/service/ShoppingCartServiceImpl.java
> +    }
@Transactional. You make more than one call to DB

2024-04-20 13:09 UTC, MAMentorFX commented on src/main/java/mate/academy/bookstore/service/ShoppingCartServiceImpl.java
> +    }
@Transactional. You make more than one call to DB

2024-04-21 09:35 UTC, okuzan approved these changes

2024-04-21 11:02 UTC, merged