implemented controller, mapper, dto
LaverAndrii/Book-Store pull request #2
Opened 2024-03-07 11:00 UTC by LaverAndrii

2024-03-07 18:26 UTC, Vasul-Pankiv requested changes

2024-03-07 18:26 UTC, Vasul-Pankiv commented on src/main/java/mate/academy/bookstore/repository/BookRepositoryImpl.java
Try to use JpaRepository it will simplify your code

2024-03-08 10:42 UTC, LaverAndrii commented on src/main/java/mate/academy/bookstore/repository/BookRepositoryImpl.java
But using JpaRepository is a task for Spring Data JPA topic

2024-03-09 14:34 UTC, kerrrusha approved these changes

2024-03-09 14:34 UTC, kerrrusha commented on src/main/java/mate/academy/bookstore/repository/BookRepositoryImpl.java
ok

2024-03-10 20:16 UTC, merged